# Generated by Django 4.2.29 on 2026-03-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_subteam_attendancerecord_document_memberguide_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cios_affiliations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated list of CIOs this user belongs to.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_meeting_attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rank_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific position (e.g., Member, Treasurer, President).",
                max_length=100,
            ),
        ),
    ]
