# Generated by Django 4.2.29 on 2026-03-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_event_constitutionsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="setup_complete",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed initial role selection after signup.",
            ),
        ),
    ]
