# Generated by Django 5.2.12 on 2026-04-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_user_administrator',
            field=models.BooleanField(default=False, help_text='Designates a backend-managed User Administrator for role management only.'),
        ),
    ]
