# Generated by Django 5.2.12 on 2026-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_is_user_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'Document Management'), ('onboarding', 'Exec Onboarding')], default='general', max_length=20),
        ),
    ]
